sudo: required
services: 
  - docker

before_install:
  - docker build -t mullerj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mullerj/react-test npm test -- --coverage

after_success:
  - docker build -t mullerj/multi-client ./client
  - docker build -t mullerj/multi-nginx ./nginx
  - docker build -t mullerj/multi-server ./server
  - docker build -t mullerj/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mullerj/multi-client
  - docker push mullerj/multi-nginx
  - docker push mullerj/multi-server
  - docker push mullerj/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-468883350109"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID

